title: Michael DeHaan's Personal Website
description: >
  Welcome to my personal website! This is a space to showcase 
  my projects, skills, and in a meta twist, the website itself is a project. 
  Feel free to explore and check out what I'm working on.